# Generated by Django 4.2.6 on 2023-10-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
